export const ESLINT_BOUNDARIES_ELEMENTS = {
  LIBS: 'libs',
  CONTROLLERS: 'controllers',
  ROUTERS: 'routers',
  DOCS: 'docs',
  UTILS: 'utils',
  TYPES: 'types',
  CONSTANTS: 'constants',
  SHARED_DOCS: 'shared-docs',
  SHARED_REPOSITORIES: 'shared-repositories',
  SHARED_SERVICES: 'shared-services',
  SHARED_ROUTERS: 'shared-routers',
  GENERATED_PRISMA: 'generated-prisma',
  APP: 'app',
  E2E: 'e2e',
  MIDDLEWARE: 'middleware',
}

export const globalTypes = [
  ESLINT_BOUNDARIES_ELEMENTS.LIBS,
  ESLINT_BOUNDARIES_ELEMENTS.UTILS,
  ESLINT_BOUNDARIES_ELEMENTS.TYPES,
  ESLINT_BOUNDARIES_ELEMENTS.CONSTANTS,
]

export const featureElements = [
  ESLINT_BOUNDARIES_ELEMENTS.CONTROLLERS,
  ESLINT_BOUNDARIES_ELEMENTS.DOCS,
  ESLINT_BOUNDARIES_ELEMENTS.ROUTERS,
]

export const sharedElements = [
  ESLINT_BOUNDARIES_ELEMENTS.SHARED_SERVICES,
  ESLINT_BOUNDARIES_ELEMENTS.SHARED_ROUTERS,
  ESLINT_BOUNDARIES_ELEMENTS.SHARED_DOCS,
  ESLINT_BOUNDARIES_ELEMENTS.SHARED_REPOSITORIES,
]
