/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InvitesInvitesIdIndexRouteImport } from './routes/invites/$invitesId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitesInvitesIdIndexRoute = InvitesInvitesIdIndexRouteImport.update({
  id: '/invites/$invitesId/',
  path: '/invites/$invitesId/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/invites/$invitesId/': typeof InvitesInvitesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/invites/$invitesId': typeof InvitesInvitesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/invites/$invitesId/': typeof InvitesInvitesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/invites/$invitesId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/invites/$invitesId'
  id: '__root__' | '/' | '/invites/$invitesId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InvitesInvitesIdIndexRoute: typeof InvitesInvitesIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invites/$invitesId/': {
      id: '/invites/$invitesId/'
      path: '/invites/$invitesId'
      fullPath: '/invites/$invitesId/'
      preLoaderRoute: typeof InvitesInvitesIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InvitesInvitesIdIndexRoute: InvitesInvitesIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
